name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/pad-app:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/pad-app:latest
	# Since I did not found anything related to back end which was asked in the Assessment Task, therefore no Backend and FrontEnd Dockerfiles created separately

     - name: Deploy to staging
      run: |
        docker-compose -f docker-compose.staging.yml up -d

    - name: Run integration tests
      run: |
        # Also, here there was nothing for tests. So I skipped this too.

    - name: Deploy to production
      if: github.ref == 'refs/heads/main'
      run: |
        docker-compose -f docker-compose.prod.yml up -d